#!/bin/bash

echo "SketchyBar Starting..."
# Paths
PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEMS_DIR="$CONFIG_DIR/items"

source "$CONFIG_DIR/colors.sh" # Loads all defined colors

##### Bar Appearance #####
sketchybar --bar position=top \
                 height=40 \
                 blur_radius=30 \
                 color=$BAR_COLOR

##### Changing Defaults #####
default=(
  padding_left=5
  padding_right=5
  icon.font="Hack Nerd Font:Bold:17.0"
  label.font="Hack Nerd Font:Bold:14.0"
  icon.color=$WHITE
  label.color=$WHITE
  background.color=$ITEM_BG_COLOR
  background.corner_radius=5
  background.height=25
  icon.padding_left=10
  icon.padding_right=10
  label.padding_left=4
  label.padding_right=4
)
sketchybar --default "${default[@]}"

# -- Right Side Items --
source "$ITEMS_DIR/calendar.sh"
source "$ITEMS_DIR/volume.sh"
source "$ITEMS_DIR/battery.sh"
source "$ITEMS_DIR/cpu.sh"

# -- Left Side Items --
sketchybar  --add item apple_logo left \
            --set apple_logo    icon="􀣺" \
                                background.color=$BAR_COLOR \
                                background.padding_left=0 \
                                background.padding_right=20 \
                                icon.padding_left=0 \
                                icon.padding_right=0

source "$ITEMS_DIR/space.sh"
source "$ITEMS_DIR/front_app.sh"

# -- Right Side Of Notch Items --
source "$ITEMS_DIR/media.sh"


# -- Left Side Of Notch Items --

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
